### ISSUE TITLE
Issues with NTP sync

### ISSUE THREAD

**Issue by Andreag00** [mikenye/docker-planefinder#20]
Hi, a few days ago my container update via watchtower and now it's having issues with syncing to PlaneFinder's NTP servers. I had to rollback to a quite old version to get the container back to working. I'll attach logs so you can clearly see what happens at startup. 

[_pfclient_logs.txt](https://github.com/sdr-enthusiasts/docker-planefinder/files/8522696/_pfclient_logs.txt)

My setup is the standard docker compose with some added labes to make traefik work. I'm using piaware as the beasthost on port 30005.

**Comment by kx1t** [comment]
Closing this issue because it's stale - feel free to reopen if it still occurs
