### ISSUE TITLE
Client memory leak

### ISSUE THREAD

**Issue by jrbenito** [mikenye/docker-planefinder#21]
Hi, 

First of all thanks for containerize this feeder client.

I notice that Planefinder container increases its memory usage steadily over the course of its life cycle. After few days running the container memory usage was above 200MB. If I restart the container, it starts around 3MB of allocated memory and keep increasing slowly and slowly. For instance, I did restart it today about 6 hours ago and now it is already using ~30MB:

![image](https://user-images.githubusercontent.com/129570/187117883-a9c4c636-ee2d-4a38-815c-17f7bf7dba08.png)

This strongly suggests a memory leak in the client or other component running inside the container. Since the system is now running on a Intel Core PC, I don't know exactly if the problem is in the client or the QEMU emulator being used to run it inside the container.

Do you have any idea? Did you notice any similar behaviour running native on a RPi? (I just update the container today and it is still happening)

I will try build native PC client docker image to try out. I will post here whatever I find.

**Comment by jrbenito** [comment]
Testing with AMD64 native client instead of using qemu to run armhf client in amd64 hardware:

After 11 hours running, the client allocate/release memory as necessary. It reached some 7MB or so while I was accessing the web ui and shrink back to 5.5MB where it is still. This behaviour never happens with  the qemu+armhf client, in this case memory keeps going up denoting a leakage. 

The PR #22  have a solution to download and install both clients into the image while choosing the proper one at build time. I will modify this solution to chose the binary at run time.

**Comment by mikenye** [comment]
Hi @jrbenito, thanks so much for raising this, and taking the time to submit a PR. It is greatly appreciated.

The reason we had standardised on the armhf binary (and qemu for non-ARM platforms) was because planefinder don't always release each architecture's versions in lock step, which makes versioning the containers very difficult.

The way versioning is done, is during the `docker build`, the version of `pfclient` is captured and written to a file within the image:

From the [Dockerfile](https://github.com/sdr-enthusiasts/docker-planefinder/blob/16b0bd53717a4c4665bf9ca9906b3cd5f8064094/Dockerfile#L51-L56):

```bash
    if /usr/local/bin/pfclient --version > /dev/null 2>&1; \
        then echo "pfclient $(/usr/local/bin/pfclient --version | head -1 | rev | cut -d " " -f 1 | rev)" >> /VERSION; \
        else echo "pfclient $(qemu-arm-static /usr/local/bin/pfclient --version | head -1 | rev | cut -d " " -f 1 | rev)" >> /VERSION; \
        fi \
        && \
    grep 'pfclient' /VERSION | cut -d ' ' -f2- > /CONTAINER_VERSION && \
```

And then the version pulled from this file during the [deploy action](https://github.com/sdr-enthusiasts/docker-planefinder/blob/16b0bd53717a4c4665bf9ca9906b3cd5f8064094/.github/workflows/deploy.yml#L98-L102):

```yaml
      # Get version from "latest"
      - name: Get latest image version
        run: |
          docker pull "${{ env.DOCKERHUB_REPO }}/${{ env.DOCKERHUB_IMAGE }}:latest"
          echo "VERSION_TAG=$(docker run --rm --entrypoint cat "${{ env.DOCKERHUB_REPO }}/${{ env.DOCKERHUB_IMAGE }}:latest" /CONTAINER_VERSION)" >> $GITHUB_ENV
```

What I'm cautious of, is that if the armhf version is (for example) 1.9, and the amd64 version is (for example) 1.8 - then this will break versioning of the multiarchitecture container.

Do you have any thoughts on how we can address this?

**Comment by mikenye** [comment]
One possibility is that we have a `:latest` tag that just contains the latest binary for all platforms, regardless of version. Then we do away with versioned multi-arch builds, and just have versioned per-architecture builds...

**Comment by jrbenito** [comment]
Hi @mikenye, it is my pleasure to contribute just a little to great work you've have done.

Regarding the version isssue, I don't see immediately any solution. However, I agree with `:latest` containing the latest binary for any platform is an easy solution that might work just out of the box.

However, right know I am in doubt if it worth doing. Contrary to what I've stated before, the AMD64 client does still leak some memory, although in slowly. It is now running around 20MiB after being up for 22 hours and, it is not shrinking, it is actually slowly increasing overtime. It indeed expanded and shrink couple of minutes after I started it and stayed almost the same for the first 10 hours or so, during rest of yesterday and today business hour it gained 15MiB. In that matter, native AMD64 binary is more gentle at CPU usage and in memory allocation, mostly, I can safely guess, due to emulation not imposing another layer of abstraction. Indeed this is a good thing, but the leakage is not tied to emulation but to the binary itself (what we have zero control over).

All that being said, maybe a more straightforward solution would be simply suggesting to limit the maximum allowed memory to that container. If the maximum is reached, docker would kill and restart the container. While not much elegant, would prevent the system to get out of memory after some while.

Please, allow me one more day to ramp up the same stack on a RPi and see if I get the same behaviour there. If so, we discuss if this worth pursuing or a simple suggestion on limiting memory for that particular container. (challenge is: what is a reasonable number?)

Just for documenting purposes, here is my stack running for the last 23 hours and memory consumption of each: 

![image](https://user-images.githubusercontent.com/129570/187335877-6f90c130-ded8-46be-b577-5e5ffa44c292.png)
(AMD64, all containers default from SDR-enthusisasts besides the pfclient being modified accordig to PR #22)

**Comment by jrbenito** [comment]
Worth mention that other containers as memory stable, they are always in this ballpark.

**Comment by mikenye** [comment]
It's a team effort! :-)

I like the idea of limiting the memory. We could include this in the healthcheck, so that existing installs with watchtower still restart the container without any user interaction or config changes.

We can also add the memory limit config to the git book and examples in the readme. 

Take your time, there's no rush.

**Comment by Freekers** [comment]
I'm observing the same issue using the latest tag (as well) on Ubuntu 22.04.
After almost 3 weeks, the container consumed almost 10GB of memory. Restarting the container indeed solves the issue temporarily, but the memory keeps climbing gradually over time again.

**Comment by jrbenito** [comment]
I am running the native client on RPi (ARM64) and indeed it also increases the memory usage although not at the fast pace observed in the PC. Comparing the native X86 client, it has exactly the same behaviour as the Pi client.

Why the qemu arm64 running on a X86 pc does consume more?
The emulation stuff uses a lot more memory (not huge deal on PC - unless it is 10GB as observed by @Freekers), hence I guess it accelerates the effect of the leak present in the client.

@Freekers are you able to test the effect of putting a memory barrier on the container?

This could be accomplished by adding `--memory=200m` to the execution line as `docker run --memory=150m [...]` or by adding `mem_limit: 200m` to the service section of the compose file.

**Comment by jrbenito** [comment]
As comparison, after 8 days running continuously on Pi, it is still 7MB although it is climbing a bit over time.

I lost another measurement of about 10 days because a power loss, I turned the pi of by mistake.

**Comment by Freekers** [comment]
@jrbenito I've just set the memory limit to 2GB, as the container manages to consume 1GB per day. Let's see if this workaround 'solves' the issue for now. Thanks!

**Comment by jrbenito** [comment]
> @jrbenito I've just set the memory limit to 2GB, as the container manages to consume 1GB per day. Let's see if this workaround 'solves' the issue for now. Thanks!

The rational behind this is at least protect your machine from having all memory drained. In parallel I am submitting a PR that have the X86 native client alongside the ARM one which will make the memory consumption less of an issue in the PC but brings trouble on how the team controls the version of the container.

**Comment by CreeperFace00** [comment]
Any updates regarding this? Got alerts that several of my services went down, turns out PF was using ~40gb of memory after running for about 24 hours and the OOM killer kicked in 😅

**Comment by kx1t** [comment]
we are now using the native amd64 build for this container - will close this issue; feel free to reopen if it persists.
https://github.com/sdr-enthusiasts/docker-planefinder/pull/76
