### ISSUE TITLE
error while loading shared libraries: libpthread.so.0: ELF load command address/offset not page

### ISSUE THREAD

**Issue by totalhavoc** [mikenye/docker-planefinder#34]
New install on raspberry pi 5 (arm64) on Bookworm 64bit, receiving the following error when trying to created a site id or just running the container:

error while loading shared libraries: libpthread.so.0: ELF load command address/offset not page

**Comment by fredclausen** [comment]
Thanks for the report. Let me look in to this, as I suspect the issue is related to the most recent image updates we've done the fix may take me a minute to track down.

**Comment by totalhavoc** [comment]
So, it seems to be an issue with the new raspberry pi 5 kernel and its use of 16k pages instead of 4k. I changed the kernel from kernel_2712.img to kernel8.img and it is working now. From what I understand the only way to fix this with the new kernel is for the pfclient to be updated by planefinder to support it. 

Changes to /boot/firmware/config.txt:

[pi5]
kernel=kernel8.img

**Comment by fredclausen** [comment]
That is really interesting. I was struggling to figure out how to replicate the issue, as I wasn't seeing it on any of my machines.

**Comment by fredclausen** [comment]
I added a note to the readme about this in #36 until PF updates their client.

**Comment by fredclausen** [comment]
Also I suppose it's important to know, what exact OS are you running? I'm assuming the latest raspbian?

**Comment by totalhavoc** [comment]
Raspbian Bookworm 64bit

**Comment by eiddor** [comment]
@totalhavoc Are you still having the issue?  I just ran into it today and I'm wondering the impact of changing kernels and if you've had any issues with that workaround.

**Comment by wiedehopf** [comment]
Someone on discord reported getting rid of this issue by using this image version:
```
ghcr.io/sdr-enthusiasts/docker-planefinder:5.0.161_arm64
```
https://github.com/sdr-enthusiasts/docker-planefinder/pkgs/container/docker-planefinder/109786253?tag=5.0.161

That's 9 months old, right before the container baseimage was changed to bookworm?

**Comment by eiddor** [comment]
That worked!  I'll put a note in the guide along with my other changes.  Thanks!
